eslint/eslint.org

src/content/pages/index.html

I haven't confirmed this by attempting a build, but I think you want it dynamic like this as presumably one wishes the site to tout the newer 23.5 million over the currently listed 6.5 million.

docs: make further weekly downloads numbers dynamic

---

src/_includes/layouts/base.njk

`og:image` is url, not path.
https://ogp.me/
SVG is not supported at twitter card.
https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image

fix: og:image

---

src/content/pages/index.html

We were duplicating the same sentence in two places, so I changed one to something different.

fix: Clean up text on homepage and reduce duplication

---

src/assets/css/components/navigation.css
src/assets/css/styles.css
src/assets/scss/components/navigation.scss

I noticed the navigation links don't take up the entire width on  mobile, so I made them so in order to increase the tappable area.

feat: increase tappable area on mobile nav links

---

src/_data/donations.json
src/_data/sponsors.json
tools/fetch-sponsors.js

This just updates the script to fetch one-time donations to use the new Open Collective API for doing so. Instead of making multiple requests and filtering, we can now just request the one-time donations directly. :tada:

chore: More efficient donations fetch script

---

src/assets/css/styles.css
src/assets/scss/donations.scss
src/content/pages/donate.md

fix: invert Github logo in dark mode

---

src/assets/scss/homepage.scss

This fixes the horizontal scrolling on mobile on the homepage. I reproduced on Safari mobile on iOS 15.3.1.
This was due to the cursor overflowing to the right. I fixed it by adding an `overflow-y: hidden` to the home page.
I'm happy to amend if you think this should be fixed differently 😊
**Before:**
**After:**

fix: remove homepage horizontal overflow on mobile

---

src/_data/sites/en.yml
src/_includes/components/header-animation.njk
src/_includes/layouts/base.html
src/assets/js/animation.js
src/content/pages/index.html

This pulls out the animation information into the `en.yml` file so we can customize it per language. I'm guessing in some languages it won't make much sense, so there's also an option to disable the animation altogether.

chore: Extract animation logic

---

src/assets/scss/components/carbon-ads.scss
src/content/pages/index.html

Avoids shifting content to the bottom when the ad pops up
Before:
https://user-images.githubusercontent.com/32865581/158005633-f1ff5ccd-1d90-457b-b747-357213d97591.mov
After:
https://user-images.githubusercontent.com/32865581/158005690-01cbb6c3-dc0e-4cf6-9a50-c244d496bd00.mov

chore: fix layout shift

---

src/_data/sites/en.yml

Just a mistake I noticed while translating the file.

Fix typo in branding page

---

src/static/_redirects

Addresses:
- https://github.com/eslint/new.eslint.org/issues/139

chore: added redirects

---

src/_includes/components/navigation.html

Lighthouse scores improved as well
Before:
https://user-images.githubusercontent.com/32865581/158770541-db2818f9-9b66-4ae9-a289-ec22d84b96b9.mov
After:
https://user-images.githubusercontent.com/32865581/158770834-482c4560-0f68-4d26-aa31-dbdd66199d0d.mov
No shifts at all

chore: Fixes layout shift in mobile caused due to topnav

---

src/static/robots.njk

The robots.txt file needs a fully-qualified URL. We were generating an invalid robots.txt file because `metadata.url` was not defined.

fix: robots.txt URL

---

netlify.toml

Now that we have a data fetch [running nightly](https://github.com/eslint/new.eslint.org/blob/main/.github/workflows/data-fetch.yml), we don't need to do a data fetch at build time.
This will reduce our Netlify build minutes (of which we do have a limit), which will be helpful as we continue to add new translation sites.

chore: Simplify build command

---

src/assets/js/search.js

We need to filter the Algolia search so it only shows blog posts on the blog index page. I'm pretty sure this will do the trick (based on [the docs](https://www.algolia.com/doc/api-reference/api-parameters/filters/#examples), but want to double-check with deploy preview.

fix: Ensure search only searches blog posts

---

src/assets/scss/components/theme-switcher.scss

Before: 
- https://github.com/eslint/new.eslint.org/issues/197
After: 
No breakage in other languages as well 
This `flex: 0` is not needed for that button I guess

fix: theme buttons in chinese

---

src/_includes/layouts/base.html
src/assets/js/themes.js

When the site loads and no theme is set in the localstorage the site flashes between dark and light mode (when the system is in dark mode)
- set system theme as dark mode and clear the site's localstorage
- reload the page the page might flash 
Removed some code that are same as the one we already have inside layout
- https://github.com/eslint/new.eslint.org/blob/824c4bf34390a5781dc69f2ca993a873e37d4e15/src/_includes/layouts/base.html#L67-L74
Before: 
https://user-images.githubusercontent.com/32865581/164293001-dac07d15-1a86-4837-8205-a5257f6e42e7.mov

fix: theme flashing

---

src/static/redirects.njk
src/static/robots.njk

This changes makes both `robots.txt` and `_redirects` site-aware. Specifically:
1. Disallows crawlers for any site that has "new." in the hostname, such as new.eslint.org and new.cn.eslint.org, because these sites are effectively in beta and we don't want Googlebot to crawl those while eslint.org and cn.eslint.org are active. All other translation sites are allowed to be crawled.
2. Automatically includes a redirect from /blog in all translations to the English /blog entrypoint. We aren't translating blog posts, so this will make sure all of the SEO power goes to the active blog posts on eslint.org.
3. Added a redirect from /demo to /play.

chore: Update robots.txt and _redirects

---

src/assets/js/components-index.js
src/assets/js/docs-main.js
src/assets/js/main.js

use addEventListener() instead of matchMedia().addListener() since matchMedia().addListener() is deprecated.

chore: replace addListener with addEventListener

---

src/assets/js/themes.js

**Current behavior:** 
Theme not set initially both light & dark theme animated dropdowns are shown. Below I have attached screenshots for your reference.
| In desktop  | In mobile |
| ------------- | ------------- |
| <img width="420" alt="image" src="https://user-images.githubusercontent.com/30730124/167247781-ee51fd61-eda6-4a7e-9cf1-d26a4614bb35.png">  |  <img width="240" height="480" alt="image" src="https://user-images.githubusercontent.com/30730124/167248023-9665e3dd-aefd-4dc2-b15d-414c38e8f206.png">  |  
**Steps to reproduce:**
When we open the website for the first time this bug will be reproduced when the theme is not selected on your device or when then the theme is light.
Device: MacBook Pro 2019 
OS: macOS Big Sur 
Browser: Chrome Version 100.0.4896.60
Ref: …

fix: set default theme

---

src/assets/scss/header.scss

**Description:**
In mobile view logo-link is not working it is not redirecting to the homepage. 
**Why it is not working in mobile view?**
In mobile view, site-navbar takes up the full width the logo-link element goes behind the site-navbar element. So the logo link is not clickable. 
**Steps to reproduce:**
Open the [new.eslint.org/team](https://new.eslint.org/team/) website on mobile and click on the eslint logo (logo-link element) in the navbar. 
Expected behavior: It should redirect to the homepage [new.eslint.org](https://new.eslint.org)
Actual behavior: Eslint logo is not clickable.
Device details:
OS: Android v10
Browser: Chrome 101.0.4951.41
Mobile device-width: <679px
**Fix:**
stacked the logo-link element on the top.
Note: There are multiple ways to fix this issue. Adding a …

fix: Redirect to homepage on logo-link click

---

src/_data/links.json

Updated the header link for the Playground to go to /play instead of the demo.

feat: Use playground in navigation

---

src/static/redirects.njk

This enables proxying to the docs site from `/docs`

feat: Enable proxying to docs site

---

src/assets/scss/components/pagination.scss
src/assets/scss/components/slider.scss

**Changes:**
Disallow the cursor when the tag is disabled.
**Before:**
**After:**

fix: disallow cursor for disabled tag

---

src/assets/scss/components/slider.scss

The slider below the testimonial is getting overlapped with the content if the content has more lines in the desktop view. This can be currently seen in French and Spanish sites. 
Before :
After :

fix: overlapping slider nav

---

src/static/redirects.njk

This adds in appropriate redirects for all sites.
For English:
* `/docs/head/` redirects to the latest built version of the docs from the `eslint` repo.
* `/docs/latest` redirects to the latest release version of the docs (the `latest` branch on the `eslint` repo)
* `/docs/` redirects to `/docs/latest`
For other sites:
* `/blog` redirects to the English site
* `/demo` redirects to the English site
* `/play` redirects to the English site
* `/docs` redirects to the English site

chore: Redirects for version-specific docs

---

package.json

use `watch:sass` instead of `build:sass` and `npm-run-all` requires only one `--parallel`

build: compress build css and remove unwanted parallel

---

src/_includes/components/navigation.html
src/_includes/layouts/base.html
src/assets/scss/components/index.scss
src/assets/scss/components/navigation.scss
src/content/pages/index.html

**Description:**
Show navbar elements when the script is disabled and reduce cls
Before:
Navbar list elements were not shown when js was disabled.
https://github.com/eslint/new.eslint.org/pull/167 reduces layout shift in mobile view but hiding navlist by default causes issue when script is disabled.  
After:

fix: show navlist when script disabled

---

.eleventy.js
src/content/pages/branding.html
src/content/pages/donate.html
src/content/pages/index.html
src/content/pages/languages.html
src/content/pages/sponsors.html
src/content/pages/team.html
src/static/robots.njk
src/static/sitemap-index.njk
src/static/sitemap.njk

Fixes #232
This PR:
* Fixes URLs in `<loc>` tags of the sitemap to be absolute as required by https://sitemaps.org/protocol.html.
* Fixes code that generates `<changefreq>` in the sitemap. It was always empty (`<changefreq></changefreq>`), which is technically invalid against https://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd
* Adds `sitemap-index.xml` file in the root. It will contain references to `https://eslint.org/sitemap.xml` and `https://eslint.org/docs/latest/sitemap.xml`. On translation sites, it will contain only one reference, e.g, `https://es.eslint.org/sitemap.xml`.
* Updates `robots.txt` to point to `sitemap-index.xml` instead of `sitemap.xml`.
* Also removes blank line between `User-agent` and `Disallow`, as blank lines are delimiters.
* ~Disables generating sitemaps …

feat: add sitemap index file

---

src/_data/all_authors.json
src/content/blog/2022-02-11-eslint-v8.9.0-released.md
src/content/blog/2022-02-23-paying-contributors-sponsoring-projects.md
src/content/blog/2022-02-25-eslint-v8.10.0-released.md
src/content/blog/2022-03-11-eslint-v8.11.0-released.md
src/content/blog/2022-03-25-eslint-v8.12.0-released.md
src/content/blog/2022-04-08-eslint-v8.13.0-released.md
src/content/blog/2022-04-22-eslint-v8.14.0-released.md
src/content/blog/2022-05-06-eslint-v8.15.0-released.md
src/content/blog/2022-05-20-eslint-v8.16.0-released.md
src/content/blog/2022-06-03-eslint-v8.17.0-released.md
src/content/blog/2022-06-17-eslint-v8.18.0-released.md

Synchronizes the blog posts with the current website and adds `eslintbot` into the `all_authors.json` file so we can use that as a placeholder wherever we want.

feat: Update blog posts and authors file

---

src/_data/sites/en.yml

For when we do the final switchover.

feat!: Switch domain name to eslint.org

---

src/_includes/components/header-animation.njk
src/content/pages/index.html

Currently, the eslint.org landing page's "Find and fix problems in your JavaScript code" `<h1>` is not exposed at all to assistive technologies such as screenreaders. From what I can tell, this seems to be out of a desire to not burden screenreader users with the red-squiggly-fixing animation, but it means that screenreader users don't get access to the heading contents at all.
To remedy this, I've removed the `aria-hidden` from the `<h1>`, and instead placed it on each of the animated child nodes. Additionally, I've added a visually-hidden span which contains the full, unbroken text contents of the heading.

fix: Ensure landing page h1 element is exposed to assistive technologies

---

src/assets/scss/components/carbon-ads.scss

Minor adjustment to the style to match the site overall theme.
- Remove the text underline
- Set the font-size smaller with dynamic line-height
- Set the hover color to match the CSS `--link-color`
@nzakas kindly review and feel free to make adjusment as needed.

chore: Improve Carbon ad style

---

src/_data/all_authors.json

Builds are failing as bot removed author from all_authors.json file. Try pulling the latest commit even `yarn start` fails. So adding author again 
- https://github.com/eslint/eslint.org/commit/b1a886fd512fc37113d040eeb6eb1d2946919d5f

add `captbaritone` to author

---

src/_data/sites/ja.yml

Adding a translation of "from_the_blog" snippet in Japanese.
(Referencing PR <https://github.com/eslint/eslint.org/pull/253>)

Adding 'from_the_blog' snippet translation in ja

---

src/_data/all_authors.json
tools/fetch-team-data.js

This ensures that existing authors are never deleted from the `all_authors.json` file. Also restored the `eslintbot` entry.
Fixes #238

chore: Ensure authors are never overwritten

---

src/content/blog/2022-07-06-interesting-bugs-caught-by-no-constant-binary-expression.md

The parens here make the bug look more obvious than it was. In the actual code they weren't present. (I must have copy/pasted incorrectly).

fix: Remove parentheses in example that were not present in actual code

---

src/_includes/partials/from-the-blog.html

Just changing the hard-coded word "View all posts" by: view_all_posts for blog page

fix: set reference to view_all_posts

---

src/assets/scss/components/playground-configuration.scss

Not sure why the share url button is not extended to full width in this case,
1. it's sort of small, I can only see `https://eslint.org/play/#e`,
2. the `vw` is not consistent, it's changing with the size of viewport, and could cause overlapping problem between the texts and copy button, you can see it from the first screenshot
Thus I'm proposing some changes to the share url button.

feat: optimize share url button

---

webpack.config.js

Related docs - https://webpack.js.org/configuration/cache/
With cache, the webpack re-build time is now reduced from `12349 ms` to `323 ms`. 
Initial build without cache:
Re-build with cache

build: enable webpack persistent cache

---

src/content/blog/2022-08-05-new-config-system-part-2.md

In two places, the config array is referred to as being "returned", while it is rather being exported. While this a minor nitpick, I was confused for a second trying to find what's being returned. An exported array could probably be said to be returned, but since `export` and `return` are JavaScript concepts that are different in many ways, I think it makes sense to use the accurate terms.

feat: update wording of flat config blog post

---

src/_includes/layouts/base.html

TypeError on the playground page is fixed. for #298

fix: Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')

---

package-lock.json
src/_data/sites/de.yml
src/_data/sites/en.yml
src/_data/sites/hi.yml
src/_data/sites/pt-br.yml
src/_data/sites/zh-cn.yml
src/_includes/components/language-switcher.html
src/_includes/partials/languages-list.html

This uses the property language names in the dropdown and languages list while providing an English-language fallback as the `title` attribute.

feat: Use property language names

---

src/_data/sites/zh-hans.yml

The SSL certificate for [new.cn.eslint.org](https://new.cn.eslint.org) has been having problems, while [zh-hans.eslint.org](https://zh-hans.eslint.org) is already available. So let's switch it.
---
Chinese site build looks like a problem with the environment variable

chore: rename `zh-cn` to `zh-hans`

---

src/assets/js/search.js
src/assets/scss/components/search.scss

- Added keyboard navigation of blog search results using `ArrowUp` and `ArrowDown`
- Pressing `Enter` on selected result will open the selected page
- Pressing `Esc` key will close the search results dropdown and focuses the input
- Added `⌘ + K` key binding to focus the search field
Closes #309

feat: add keyboard controls to blog search

---

src/_includes/components/card.macro.html

Previously both cover and title could be reachable via keyboard navigation, but in fact both pointed to the same link. This is not accessibility friendly. Let's focus only on the more important title.
---
| Before | After |
| - | - |
| ![before](https://user-images.githubusercontent.com/45708948/185859968-cb7dc7ad-b223-43ac-90aa-051bbf4cb192.gif) | ![after](https://user-images.githubusercontent.com/45708948/185860014-60d0abbb-4dd6-4865-80c0-e07357a10a71.gif) |

feat: make card cover can't reachable via `Tab`

---

src/content/blog/2022-08-08-new-config-system-part-3.md

Corrects the syntax for importing FlatESLint.

fix: ESM import syntax in blog post

---

src/content/blog/2022-09-12-eslint-v8.23.1-released.md

This ended up being a patch release, so no highlights, but I still need to un-draft the release notes.

docs: Publish v8.23.1 release notes

---

src/_includes/layouts/post.html

This seems to be a mistake where anchors were generated for sidebar headings as well (those red ones).
I think it should only target the blog content, i.e., the green part.

fix: update css selector for anchors

---

package-lock.json
src/_data/links.json
src/_data/sites/de.yml
src/_data/sites/en.yml
src/_data/sites/es.yml
src/_data/sites/fr.yml
src/_data/sites/hi.yml
src/_data/sites/ja.yml
src/_data/sites/pt-br.yml
src/_data/sites/zh-hans.yml
src/static/redirects.njk

This enables individual sites to refer to their own documentation sites. zh-hans is the first locale that has its own documentation site, so that is the only one that is enabled.

feat: Add zh-hans docs

---

.stylelintrc.js
src/assets/scss/animation.scss
src/assets/scss/components/carbon-ads.scss
src/assets/scss/components/playground-configuration.scss
src/assets/scss/components/popup.scss
src/assets/scss/components/search.scss
src/assets/scss/forms.scss
src/assets/scss/homepage.scss
src/assets/scss/languages.scss
src/assets/scss/syntax-highlighter.scss
src/assets/scss/versions.scss

Same as https://github.com/eslint/eslint/pull/16466

chore: enable `stylelint declaration-block-no-duplicate-properties`

---

src/playground/components/Popup.js

Open docs in a new tab. Because as a user I want to look at the code in the editor and docs back and forth.
Currently, this is also the behavior of links in the console.

fix: open rule docs in new tab from the Popup component

---

src/_data/sites/en.yml
src/static/redirects.njk

This change ensures that docs.eslint.org and cn.eslint.org redirect to the correct place.
DNS is set up so that both docs.eslint.org and cn.eslint.org point to eslint.org. The intended outcome is that entering either of these two domain names will result in a redirect to the correct location.
docs.eslint.org should redirect to eslint.org/docs/latest/
cn.eslint.org should redirect to zh-hans.eslint.org
Fixes #368

fix: Redirect docs.eslint.org and cn.eslint.org

---

package.json

Before the `license` filed in `package.json` is `ISC`, but `LICENSE` file is shown as Apache. So we should correct it.

fix: show correct license in `package.json`

---

.github/labeler.yml
.github/workflows/label.yml

Similar to https://github.com/eslint/eslint/pull/16615
Automatically label new pull requests based on the paths of files being changed.

chore: automatically add label

---

src/assets/scss/components/language-switcher.scss
src/assets/scss/components/social-icons.scss

Fixed footer socials icon with nowrap
<details>
<summary>Homepage</summary>
</details>
<details>
<summary>Playground</summary>
</details>
Ref https://github.com/eslint/eslint.org/pull/381#issuecomment-1349514328

fix: footer social icons layout with nowrap

---

src/_data/donations.json
src/_data/sponsors.json
src/content/pages/sponsors.html
tools/fetch-sponsors.js

The CI [has failed](https://github.com/eslint/eslint.org/actions/runs/3770301500/jobs/6410053617) because of a `null` value of name coming from here https://github.com/eslint/eslint.org/commit/415e0bba84b8d205faa5c47924c928b0b0074dba#diff-ff108750031135fb05819cca15c41069cf217df9c9e21745012a5af2e965c55bR256.
And I can confirm it's not a glitch or something because the Web version of GitHub GraphQL API did return `null` for this sponsor:
1. Set a fallback value for `name` in template.
Currently I'm setting it to `''`, but I'm not sure it's a good option as it could mess the layout:
But it shouldn't be a problem once the data fetching is done next midnight because there's another fallback value in `fetch-sponsors.js`, see next.
2. Set the value of `name` to `login` when `null` in …

fix: use sponsor's GitHub username when name is missing

---

src/assets/js/search.js

Fixed search bar focusing on pressing Esc
SImilar to https://github.com/eslint/eslint/issues/16699 (for Blog page)

fix: searchbar focus on `Esc` key press

---

src/assets/scss/components/index.scss

The display of toggle button of navbar is none in 680px screen width while the nav-list is also hidden.
just set the media query min-width to 681px so the display of the toggle button will be none on 681px

fix: display of nav toggle button

---

src/assets/scss/components/navigation.scss
src/assets/scss/header.scss

on screen width 680px the alignment of nav-links is linear.
issue occur by my last [PR](https://github.com/eslint/eslint.org/pull/411)
changed all nav-links related media query min-width to 681px
Sorry for not testing the previous PR properly

fix: nav-links alignment

---

src/assets/js/animation.js
src/assets/scss/animation.scss

The animation image of home page is having different sizes on different languages as it is varying with the text 'Problem', because of this in some languages it's width is very large and some one has a small one.
<details>
<summary>in chinese</summary>
</details>
<details>
<summary>in french</summary>
</details>
added the `max-width` property to the image for different screen size and since with the steady width image can overflow so added the `float: right` through JavaScript on overflowing.

fix: different size of animation image

---

src/_data/all_authors.json
src/_includes/partials/author_bios/MichaelDeBoey.md
src/content/drafts/eslint-community-org.md

Adding a blogpost to announce the official ESLint Community org
I added a blogpost to announce the official ESLint Community org
N/A
Spelling, grammar & if everything's included that @nzakas wants to include.

feat: blog: ESLint Community org announcement

---

src/content/blog/2023-03-28-eslint-v8.37.0-released.md

Added highlights and published the v8.37.0 release blog post.

docs: Publish v8.37.0 release highlights

---

src/content/blog/2023-04-07-eslint-v8.38.0-released.md

Added highlights and published the v8.38.0 release blog post.

docs: Publish v8.38.0 release highlights

---

src/static/sitemap-index.njk

In https://zh-hans.eslint.org/sitemap-index.xml, adds a reference to https://zh-hans.eslint.org/docs/latest/sitemap.xml.
Before the change:
```xml
<?xml version="1.0" encoding="utf-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap>
<loc>https://zh-hans.eslint.org/sitemap.xml</loc>
</sitemap>
</sitemapindex>
```
After the change:
```xml
<?xml version="1.0" encoding="utf-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap>
<loc>https://zh-hans.eslint.org/sitemap.xml</loc>
</sitemap>
<sitemap>
<loc>https://zh-hans.eslint.org/docs/latest/sitemap.xml</loc>
</sitemap>
</sitemapindex>
```
In the sitemap index template, I replaced a condition `if site.language.code == "en"` with `if site.locals.docs_latest`. This will generate a docs …

fix: add reference to zh-hans docs sitemap

---

src/static/redirects.njk

After merging https://github.com/eslint/zh-hans.docs.eslint.org/pull/95, which included URL changes from https://github.com/eslint/eslint/pull/16665, we forgot to enable redirects (https://github.com/eslint/eslint.org/pull/388) for the zh-hans site.
Updated redirects template to enable docs IA update redirects for the zh-hans site.
Redirects from `source-code` to `development-environment` (https://github.com/eslint/eslint.org/pull/409) are still specific for the en site only because the change (https://github.com/eslint/eslint/pull/16780) was merged for v8.33.0, while the zh-hans docs site is currently synced with 8.32.0. 
No.
Please double check how this change affects the `_site/_redirects` file:
* For the zh-hans site, it should have 46 new redirect rules, the same as in …

fix: enable docs IA update redirects for zh-hans site

---

src/playground/components/CodeEditor.js

Memoize the extensions in code editor to reduce expensive calculations on every re-render
Used `useMemo` to wrap the extensions array to keep the reference.
Ref: https://www.npmjs.com/package/@uiw/react-codemirror?activeTab=readme

perf: memoize the extensions in code editor to reduce expensive calculations

---

src/static/redirects.njk

Redirects https://zh-hans.eslint.org/docs/latest/contribute/source-code to https://zh-hans.eslint.org/docs/latest/contribute/development-environment
Updated the redirects file to remove a `site.language.code == "en"` conditional that will be no longer valid after syncing zh-hans docs site with v8.33.0.
Should be merged after merging https://github.com/eslint/zh-hans.docs.eslint.org/pull/99

docs: redirect getting source code to development environment on zh-hans

---

src/content/blog/2022-08-05-new-config-system-part-2.md

We ended up removing the ability to have parsers in plugins as part of the language plugins work, so updating the blog post to avoid confusion.
https://github.com/eslint/eslint/issues/16930

docs: Remove plugin parsers

---

src/playground/App.js

This fixes a rendering issue in the playground that would occur when a rule produces multiple messages with the same `line` and `column` as described in #445.
This PR changes the key calculation for messages in the playground to ensure that each key is unique.
React requires all elements in a list to have a unique key, but the messages reported by ESLint are not necessarily distinct, thus we cannot rely on message properties only to create a unique key.
Instead of a combination of `ruleId`, `column` and `line`, I'm using the message index and the timestamp of the last lint as a key.
Fixes #445

fix: Use a unique key for each message

---

src/content/blog/2023-06-16-eslint-v8.43.0-released.md

Added highlights and published the v8.43.0 release blog post.

docs: Publish v8.43.0 release highlights

---

src/playground/App.js
src/playground/components/Configuration.js

Fixes a crash on the playground when `parserOptions` is provided as an object without `ecmaFeatures`.
Added a `?.` for attempted lookups of `parserOptions.ecmaFeatures` members.
Fixes #450
Nothing comes to mind 🙂

feat: allow partial configs in playground URL

---

src/playground/App.js

When the docs site passes only `text`, Playground currently sets stored or default `options`.
Here's an example, this link is on the first example of `array-callback-return`:
https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgYXJyYXktY2FsbGJhY2stcmV0dXJuOiBcImVycm9yXCIqL1xuXG52YXIgaW5kZXhNYXAgPSBteUFycmF5LnJlZHVjZShmdW5jdGlvbihtZW1vLCBpdGVtLCBpbmRleCkge1xuICAgIG1lbW9baXRlbV0gPSBpbmRleDtcbn0sIHt9KTtcblxudmFyIGZvbyA9IEFycmF5LmZyb20obm9kZXMsIGZ1bmN0aW9uKG5vZGUpIHtcbiAgICBpZiAobm9kZS50YWdOYW1lID09PSBcIkRJVlwiKSB7XG4gICAgICAgIHJldHVybiB0cnVlO1xuICAgIH1cbn0pO1xuXG52YXIgYmFyID0gZm9vLmZpbHRlcihmdW5jdGlvbih4KSB7XG4gICAgaWYgKHgpIHtcbiAgICAgICAgcmV0dXJuIHRydWU7XG4gICAgfSBlbHNlIHtcbiAgICAgICAgcmV0dXJuO1xuICAgIH1cbn0pO1xuIn0=
This is not desirable, options should be empty.
Updated Playground to set …

fix: use empty options in the Playground when URL contains only text

---

tools/fetch-sponsors.js

A few months ago we noticed that private sponsorships were being shown on the website. At the time, GitHub didn't have a way to filter out private sponsorships and also didn't provide any way to tell if a sponsorship was private, so we couldn't do anything about it.
I just received word that they have added in the ability to filter out private sponsorships and so I updated `fetch-sponsors.js` to do that.

fix: Exclude private sponsors from list

---

src/content/blog/2023-07-28-eslint-v8.46.0-released.md

The v flag is in ES2024, not ES2023, so I fixed that.
https://github.com/tc39/proposals/blob/main/finished-proposals.md
None

fix: typo in 2023-07-28-eslint-v8.46.0-released.md

---

tools/fetch-sponsors.js

Ensure that we are retrieving only cancelled sponsorships within the next month rather than all sponsorships that aren't active. Also updated the month timestamp logic to account for zero-based months.

fix: OC sponsors fetch for cancelled orders

---

src/assets/scss/homepage.scss

Section styled with metrics class on home page not aligned correctly on big screens more that 2600px width
fix/metrics-align-correctly-at-big-screens
- it's fixes style of a section on home page the problem shows only at extra-large screens >2600px
- add ```
justify-content: space-evenly;``` 
at homepage.scss
- before : 
- after :

fix: fix styling on home page

---

package-lock.json
package.json

Improve 11ty's development experience and stop waiting for browser reloading
https://github.com/eslint/eslint.org/blob/59836e0830fc08942d58ae2634155e2ad9a58047/package.json#L52-L54
Sience v2.0 [Eleventy Dev Server](https://www.11ty.dev/docs/dev-server/) replaces Browsersync. It starts up a lot faster.
Before this I used to have to wait for refactoring and browser page reloads when debugging pages, which took me a lot of time.
If it is accepted, it will be extended to eslint/eslint/docs

feat: upgrade to 11ty 2.0

---

src/content/blog/2023-11-07-whats-coming-in-eslint-9.0.0.md

Created a blog post announcing the significant changes in v9.0.0.
I purposely left off smaller breaking changes, especially those for which we don't have a final design, as I don't think those details are necessary for this blog post. We will, of course, need to clarify those in the release notes.
fixes #487

feat: What's coming in ESLint v9.0.0

---

src/assets/scss/sponsors.scss

Currently Sliver Sponsor images are the same size as Platinum Sponsors and larger than Gold Sponsors. This is clearly not what we intended
Reduce the size of the Sliver Sponsor's image.

fix: sliver sponsor image size is too large

---

src/assets/scss/components/language-switcher.scss
src/assets/scss/components/social-icons.scss

fix(footer): add flex-basis and flex-grow to social icons and language switcher
The theme switcher was offcentered because the language switcher is larger than the social icons section.
Before: 
After:
I applied style changes on `language-switcher.scss` and `social-icons.scss`, adding `flex-grow` and `flex-basis` properties to each. On the first one, I also applied `justify-content: end`; to bring the language switcher to the end of the flex container. It was also tested on mobile, and still works fine.
None
No

fix: Add flex-basis and flex-grow to social icons and language switcher

---

src/_data/stats.json
tools/fetch-stats.js
tools/release-data.js

* Added `release-data.js` file where we can manually specify whether the upcoming release will be a regular release or an alpha/beta/rc prerelease.
* Updated `fetch-stats.js` to use the above info when calculating the upcoming release version.
The usage should be simple:
* `"alpha"` = the upcoming release will be an alpha prerelease
* `"beta"` = the upcoming release will be a beta prerelease
* `"rc"` = the upcoming release will be an rc prerelease
* `null` otherwise.
I set it initially to `"alpha"`, as the upcoming release will indeed be an alpha prerelease.
There will be no need to change anything until we decide that the upcoming release will be a beta prerelease, at which point we should change the value to `"beta"`. The same for `"rc"`. When we decide that the upcoming release will be …

feat: show prerelease as the upcoming version

---

src/_data/sites/de.yml
src/_data/sites/en.yml
src/_data/sites/es.yml
src/_data/sites/fr.yml
src/_data/sites/hi.yml
src/_data/sites/ja.yml
src/_data/sites/pt-br.yml
src/_data/sites/zh-hans.yml
src/_data/stats.json
src/content/pages/index.html
tools/fetch-stats.js

Updates eslint.org homepage to show different versions when the current version is a prerelease:
Latest Version
Latest Prerelease Version
Upcoming Version
instead of (when the current version is not a prerelease):
Latest Version
Upcoming Version
Development
* Updated `tools/fetch-stats.js` to correctly fetch and calculate the current version and the latest version.
* Updated homepage to use this data and show different versions depending on whether the current release is prerelease, per the description.
https://github.com/eslint/eslint/issues/17893#issuecomment-1866717652
We'll need translations for "Latest Prerelease Version".

feat: show current prerelease version

---

src/_data/sites/de.yml
src/_data/sites/en.yml
src/_data/sites/es.yml
src/_data/sites/fr.yml
src/_data/sites/hi.yml
src/_data/sites/ja.yml
src/_data/sites/pt-br.yml
src/_data/sites/zh-hans.yml
src/static/redirects.njk

Updates the redirects file to enable `/docs/next/`, where we'll have the prerelease docs.
Copy-pasted and adjusted the code that handles `/docs/head/`.
https://github.com/eslint/eslint/issues/17893
Neitlify hasn't been set up yet, so this is not testable at the moment.

feat: enable `docs/next`

---

tools/fetch-stats.js

Updates logic that calculates ESLint versions for the eslint.org homepage to account for backport versions.
Updated `tools/fetch-stats.js` to sort fetched releases by `semver.rcompare` before proceeding with the calculations. This specifically account for the case that the most recently published version is a backport.
https://github.com/eslint/eslint/issues/17966

feat: account for backports when calculating versions

---

src/assets/scss/components/playground-configuration.scss
src/playground/App.js
src/playground/components/CodeEditor.js
src/playground/components/Configuration.js
src/playground/package.json
src/playground/utils/constants.js

Migration of the online playground to use flat config system.
- Update playground to use flat config.
- Removed environments.
- Supports existing links to the Playground by translating configurations to the new format.
- Updated download configuration functionality
- ~If `sourceType` is `module` then the downloaded config is in the ESM format otherwise it's in the CommonJS format.~
- Added an option to select config file format.
Fix https://github.com/eslint/eslint.org/issues/507
Should we update the default value for `sourceType` to `module`?

feat: migrate playground to flat config

---

src/_data/sites/de.yml
src/_data/sites/en.yml
src/_data/sites/es.yml
src/_data/sites/fr.yml
src/_data/sites/hi.yml
src/_data/sites/ja.yml
src/_data/sites/pt-br.yml
src/_data/sites/zh-hans.yml
src/static/redirects.njk

Updates the redirects file to enable `/docs/v8.x/`, where we'll have v8.57.0 docs.
Copy-pasted and adjusted the code that handles `/docs/head/`.
https://github.com/eslint/eslint/issues/18229

feat: enable `docs/v8.x`

---

src/static/redirects.njk

Redirecting https://eslint.org/docs/latest/use/configure/configuration-files-new to https://eslint.org/docs/latest/use/configure/configuration-files
This change should NOT be merged until we release v9.0.0 (final version, not alpha or beta) with updated docs.
https://github.com/eslint/eslint/pull/17840

feat: Redirect flat config docs to main docs

---

src/static/redirects.njk

Redirects `docs/next/*` to `docs/latest/*`. 
https://github.com/eslint/eslint/issues/18228
This should _not_ be merged before we release ESLint v9.0.0 final.
This should be merged right after we release ESLint v9.0.0 final.

feat: redirect `docs/next` to `docs/latest`

---

src/content/blog/2024-04-05-eslint-config-inspector.md
src/content/blog/2024-04-05-eslint-v9.0.0-released.md

Added the release notes for v9.0.0 and included the blog post about the config inspector.
https://github.com/eslint/eslint/issues/18228

feat: v9.0.0 release post(s)

---

src/content/blog/2024-05-09-eslint-compatibility-utilities.md

Added a blog post introducing the compatibility utilities.
https://github.com/eslint/rewrite/issues/4

feat: ESLint compat utilities post

---

src/_includes/layouts/base.html

To remove the delay on dns connection of static files from external resources
Add dns-prefetch of popular static files to speed up site performance

perf: Add dns-prefetch for static resources

---

src/playground/package.json
webpack.config.js

Updates webpack config to support `node:` protocol (e.g., `require("node:path")`).
This change is necessary in order to build the Playground from the upcoming ESLint v9.3.0 because it will use the `node:` protocol.
Updated webpack config like in https://github.com/eslint/eslint/pull/18434, as recommended in https://github.com/webpack/webpack/issues/13290.
https://github.com/eslint/eslint/pull/18434
Check that the playground is working properly in the deploy preview.

fix: support `node:` protocol when building Playground

---

src/static/redirects.njk

Fixes #545
Added a redirect from `/docs/v9.x/*` to the official latest docs URL in the redirects template.
#545

feat: redirect `docs/v9.x` to `docs/latest`

---

src/content/blog/2023-09-26-preparing-custom-rules-eslint-v9.md

Updates the blog post about the v9 rule API changes to include mention of the new `eslint-tranforms` release.

feat: Add mention of eslint-transforms to rule API blog post

---

src/assets/scss/foundations.scss
src/assets/scss/homepage.scss

Handle responsive layout of metrics in home page on ultra wide monitors/views.
Basically adding a flex wrap property to handle in the case of step-6 font being too large on ultra wide views which causes the text to get out of its parent frames.
here's a before and after screenshots
ultra wide:
wide:
normal:
extra small/mobile:

chore: Add flex-wrap property for responsive layout on homepage

---

src/assets/scss/foundations.scss

- Fix #577 
- Set [font-variant-ligatures](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures) to `none`.
- Same as [docs website](https://github.com/eslint/eslint/blob/b2d256c7356838f908c4a5762d6dc64b41bbce5d/docs/src/assets/scss/foundations.scss#L164)
No

fix: disable font ligatures in code blocks for better readability

---

.eleventy.js
eslint.config.js
package-lock.json
package.json
tools/add-author.js
tools/fetch-sponsors.js
tools/fetch-stats.js
tools/fetch-team-data.js
tools/validate-links.js
webpack.config.js

Switches to eslint-config-eslint v11 & eslint v9.5.0 for linting this repo.
Updated dependencies, updated eslint config accordingly, and updated tools, scripts and config files to use `node:` protocol.
https://github.com/eslint/eslint/pull/18560
https://github.com/eslint/eslint/pull/18434

chore: switch to eslint-config-eslint v11

---

src/content/blog/2024-06-28-eslint-v9.6.0-released.md

Added highlights and published the v9.6.0 release blog post.

docs: Publish v9.6.0 release highlights

---

src/playground/utils/constants.js

Adds 2025 to the ECMA Version list in the ESLint Playground. 
Added `2025` to `ECMA_VERSIONS` list.
https://github.com/eslint/eslint/pull/18596

feat: add ECMA Version 2025 to Playground

---

src/assets/scss/components/search.scss

Changes made:
1. Fixed the search text overlapping with the close icon
2. Correct the position of the close icon
3. Adjusted the positioning of the search results dropdown
| Before  | After |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/3fec793d-eef4-41ae-afdb-686f2408bb23) |  ![image](https://github.com/user-attachments/assets/8236a1ae-d660-4581-b4c3-ccee133dd717)  |
similar to https://github.com/eslint/eslint/pull/18682

fix:  fix search input stylings

---

eslint.config.js
package-lock.json
package.json

Updates `eslint-plugin-react` dev dependency to the latest v7.35.0 that supports ESLint v9.
Updated dependencies and removed the use of compatibility utilities with `eslint-plugin-react` in our eslint config.

chore: upgrade eslint-plugin-react@7.35.0

---

src/content/blog/2024-07-26-eslint-v9.8.0-released.md

Added highlights and published the v9.8.0 release blog post.

docs: publish v9.8.0 release highlights

---

src/content/pages/blog.html

the page number in the url of blog pages (not category wise blog pages) is one less than its original page number
blog has total 45 pages if we head over to the last page through url then it take us to error page.
change the permalink of blog pages by increasing the count by one.

fix: page number in blog's url

---

src/assets/scss/components/alert.scss
src/playground/App.js
src/playground/components/Alert.js
src/playground/components/Configuration.js

- [-] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
we can Disabled an rule quickly.
fixes https://github.com/eslint/eslint.org/issues/548
The css style is a little newbie not perfect sorry

feat: add disable rule button in playground messages

---

src/_includes/components/search.html

When searching with the search box, say I input `mjs` and press `<Tab>` key, it would focus firstly on the link of algolia which  is covered by the search result modal, then the clear button, then the result item. IMO it makes more sense to disable it from reachable via tab key.
Add `tabindex="-1"` to `<a />` element.

fix: make algolia link not reachable via tab key

---

src/_includes/components/search.html

Links should be accessible via tab. We shouldn't eliminate that. We need a different approach to solve the original problem.
Reverts eslint/eslint.org#615

Revert "fix: make algolia link not reachable via tab key"

---

src/assets/scss/components/playground-configuration.scss
src/playground/App.js
src/playground/components/Configuration.js

A "Reset" button has been added to restore the config to the default ESLint settings, matching what users see when they first open the playground.
#592 
The button is currently labelled "Revert Configs to Default," but I'm open to suggestions for a different name also.

feat: [playground] Add revert configs to default option

---

tools/fetch-sponsors.js

Siemens recently donated $1000 to ESLint through GitHub Sponsors, but it's showing up as a sponsor rather than a donation. 
This updates our script to filter out any one-time sponsorships from the sponsors list (these are displayed as individual donations rather than sponsorships).
I also fixed the sorting of donations so that the Open Collective and GitHub donations are sorted in chronological order across both data sets.

fix: Ensure donations don't show up as sponsors

---

.github/labeler.yml
.github/workflows/ci.yml
.github/workflows/label.yml

Update actions to the latest version

ci: Update the actions version to the latest

---

.eleventy.js
eslint.config.js
src/_11ty/collections/blogposts.js

A future blog post is a blog post with a publication date > current date. Those posts shouldn't appear on the site before their publication date.
Currently, if we have a future blog post merged, it indeed wouldn't appear in the list of blog posts on https://eslint.org/blog/. But it's still rendered, deployed, can be accessed, and appears in the sitemap and in the list of blog posts on its category page (e.g., https://eslint.org/blog/category/case-studies/).
Updated `.eleventy.js` to completely ignore future blog posts, so they won't be rendered and deployed.
https://github.com/eslint/eslint.org/pull/645#issuecomment-2390639224

fix: Don't deploy future blog posts in production

---

src/content/blog/2024-10-04-eslint-v9.12.0-released.md

Added highlights and published the v9.12.0 release blog post.

docs: Publish v9.12.0 release highlights

---

src/_includes/layouts/base.html
src/content/pages/version-support.md

Update the website for v8.x EOL.
- Added information for v8.x EOL to the version support page
- Updated the banner
We should merge this on October 5.

feat: Updates for v8 EOL

---

includes/sponsors.md
tools/generate-sponsors.js

In the tool that prerenders sponsors for READMEs, adds a newline after the first paragraph of the Sponsors section.
Without this, Prettier check would be failing in https://github.com/eslint/rewrite. I added it manually in https://github.com/eslint/rewrite/pull/122.
Updated `tools/generate-sponsors.js`.

chore: Update prerendered sponsors layout

---

eslint.config.js
package-lock.json
package.json

As the latest versions of eslint plugins we're using in this repo support ESLint v9.x, there's no need to use `@eslint/compat` utility.
Updated eslint-plugin-* dependencies and removed `@eslint/compat`.

chore: Upgrade eslint plugins, remove `@eslint/compat`

---

src/_data/sponsors.json
src/content/pages/sponsors.html
tools/fetch-sponsors.js

Fix sponsors display
1. Ensure that sponsors with `null` names and images are still displayed on the sponsors page
2. Ensure that sponsors who give enough money each month are properly credited in the correct tier (Cybozu was incorrectly not displayed as a bronze sponsor -- this was due to an error in `fetch-sponsors`)
The first issue was causing the website build to fail.

fix: Display and calculation of sponsors

---

src/content/blog/2024-11-15-eslint-v9.15.0-released.md

Added highlights and published the v9.15.0 release blog post.

docs: Publish v9.15.0 release highlights

---

src/assets/scss/syntax-highlighter.scss
src/assets/scss/tokens/themes.scss

Improve color contrast in code comments to WCAG AA levels.
I swapped out the hardcoded comment colors with the closest theme tokens that had sufficient contrast.
<table>
<thead>
<tr>
<th>Mode
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>Light</td>
<td><img alt="'Before' screenshot in light mode of a code block with just barely too low contrast for code comments" src="https://github.com/user-attachments/assets/ecc3e6a9-7f25-4a8e-bf7b-4fa0c355c3c4" width="315px" /></td>
<td><img alt="'After' screenshot in light mode of a code block with just barely too low contrast for code comments" src="https://github.com/user-attachments/assets/0a77ad15-ef3a-49a3-8a19-f824d00dccfe" width="315px" /></td>
</tr>
<tr>
<td>Dark</td>
<td><img alt="'Before' screenshot in dark mode of a code …

fix: use higher contrast color tokens for code comments

---

src/assets/scss/components/hero.scss

Reduce the vertical size of the "hero" to not grow in space with viewport height.
* In larger viewports that have ads, shrinks the `min-height` of the `.hero` container to be just slightly more than the size of the ad
* In smaller viewports that don't have ads, reduces padding of its child `.content-container`
Fixes #671.
There wasn't any existing calculation I could find to reuse for ad height. So I just went off the computed height locally.

feat: reduced hero vertical padding

---

src/assets/scss/components/social-icons.scss

The social icons overflow the screen, causing an unwanted scrollbar to appear.
I've reduced the gap between the icons on specific screen sizes to resolve this.
| Before | After |
--------|---------
|  ![image](https://github.com/user-attachments/assets/093b1701-ae13-4f29-bc94-ac6c15661ae5)  |  ![image](https://github.com/user-attachments/assets/c96f19c5-0de0-405f-a274-9717fbde2690)  |
|  ![image](https://github.com/user-attachments/assets/78a270c5-4dea-444f-a856-842a60e0e4c7)  |  ![image](https://github.com/user-attachments/assets/d5f4c43f-0153-4c20-833d-f6174d0a3a5a) |

fix: Overflow Issue by Adjusting Social Icon Spacing

---

src/_data/stats.json
tools/fetch-stats.js
tools/release-data.js

Adds setting to hardcode next release date.
We've decided to skip the next scheduled release on 27 Dec, and updated `stats.json` in https://github.com/eslint/eslint.org/commit/c23f0005ac8508bc7c56251e33f66ab0a95b623f to reflect that. However,  `tools/fetch-stats.js` overwrites it (https://github.com/eslint/eslint.org/commit/7582067536a4aabf4e3f0f015fe9908e75c872c8) per its logic, so there needs to be a way to specify this in the data. 
Updated `tools/fetch-stats.js` to use the new setting.

feat: add option for custom release dates

---

src/_includes/components/search.html
src/assets/js/search.js

Fixing Focus Order by Rearranging Element Sequence. 
Ref: https://github.com/eslint/eslint.org/pull/615#issuecomment-2299003407
**Before:** When using the search box, pressing the `Tab` key would first focus on the Algolia link (which was covered by the search result modal), then on the clear button, and finally on the result items.
**After:** When using the search box, pressing the `Tab` key now first focuses on the search results, followed by the close button, and then the Algolia link.

chore: Fixing Focus Order by Rearranging Element Sequence

---

src/content/blog/2025-01-10-eslint-v9.18.0-released.md

Added highlights and published the v9.18.0 release blog post.

docs: Publish v9.18.0 release highlights

---

src/content/blog/2025-01-10-eslint-v9.18.0-released.md

Switched a link to the website in the ESLint v9.18.0 release blog from `/head/` to `/latest/`. After updating the latest branch in eslint/eslint#19338 it's fine to link to the the latest version of the docs.

docs: update link in ESLint v9.18.0 release blog

---

src/_includes/layouts/base.html
src/_includes/partials/faqs.html
src/content/pages/index.html

This pull request improves accessibility by addressing WCAG 2.1 issues, including adding `role="alert"` to the deprecation notice, moving the skip-to-content link to the top of the page to comply with WCAG 2.1 [2.4.1 Bypass Blocks](https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks.html), correcting `aria-labelledby` on the FAQ section, and ensuring proper landmark usage across the page.
- Added `role="alert"` to deprecation notice for better screen reader support.
- Moved "skip to content" link before deprecation notice for improved navigation.
- Updated FAQ section with proper `aria-labelledby` for better clarity.
- Fixed `testimonials-section-label` by aligning the ID with the heading element.

fix: improve WCAG 2.1 accessibility compliance

---

src/assets/js/search.js

similar to https://github.com/eslint/eslint/pull/19424
Ref: https://github.com/eslint/eslint/issues/19381

fix: allow typing in search box while dropdown is open

---

src/content/blog/2025-02-21-eslint-v9.21.0-released.md

Added highlights and published the v9.21.0 release blog post.

docs: Publish v9.21.0 release highlights

---

src/assets/scss/blog.scss

Unlike pc screen size there is no border between author's bio and other info about blog in small screen size (below 1024px)
Added the border here

fix: add border after author's bio in blog

---

src/_data/links.json
src/_data/sites/de.yml
src/_data/sites/en.yml
src/_data/sites/es.yml
src/_data/sites/fr.yml
src/_data/sites/hi.yml
src/_data/sites/ja.yml
src/_data/sites/pt-br.yml
src/_data/sites/zh-hans.yml
src/assets/js/main.js
src/assets/scss/components/index.scss
src/assets/scss/components/navigation.scss
src/assets/scss/header.scss

Add code explorer in the navbar
Fixes https://github.com/eslint/eslint.org/issues/676

feat: add code explorer in the navbar

---

src/assets/js/search.js

Added condition to not focus on search bar when pressing enter.
https://github.com/eslint/eslint/issues/19501
Similar to https://github.com/eslint/eslint/pull/19502

fix: search navigation on pressing Enter

---

src/assets/scss/components/alert.scss
src/assets/scss/components/alerts-action-bar.scss
src/assets/scss/styles.scss
src/playground/App.js
src/playground/components/AlertsActionBar.js

Implemented a new AlertsActionBar component.
This pull request adds a new persistent bar to the top of the console, providing "Fix All" and "Disable All" buttons. "Fix All" resolves all fixable errors, while "Disable All" disables all error rules.
Closes #549

feat: add alerts action bar

---

src/playground/components/Configuration.js

- Border bottom was missing in menu dropdown
-  Cursor was not pointer  for dropdownmenu icon
No

fix: correct rule input menu styles

---

src/content/blog/2025-04-21-eslint-v9.25.1-released.md

Added highlights and published the v9.25.1 release blog post.

docs: Publish v9.25.1 release highlights

---

src/assets/scss/components/playground-configuration.scss
src/playground/components/Configuration.js

- Fixed styling of Reset Button with secondary-btn style used all over the project
NA
`Before`
`After`

fix: reset btn styling

---

src/assets/scss/components/playground-configuration.scss
src/playground/App.js
src/playground/components/Configuration.js
src/playground/components/ShareURL.js
src/playground/utils/constants.js

- Add `Report an issue` button under Share section on playground
- Prefilled `Environment` with ESLint Playground text
- Prefilled `What did you do` with code, config and output
- Prefilled `What actually happened?` with output
- Prefilled `Link to Minimal Reproducible Example` with the shareable URL
Fix for https://github.com/eslint/eslint.org/issues/598
Need opinion for the following edge case
- There is an edge case where if you enable add the rules, the config file becomes too big, and thus trying to create issue gives error of request URL too long. 
Following are the identified issues in case when all the rules were enabled
1. The shareable link which is generated (base64 config) is pretty big and we append it in the params, which when gets URL encoded becomes too big
2. We are …

feat: add report an issue button

---

src/playground/App.js

Hi,
In this PR, I’ve fixed the bug reported in #738.
After this fix, the cursor no longer jumps to the start of the line unexpectedly.
---
The source of the bug was the following code:
```js
setFix(false);
setText(value);
storeState({ newText: value });
```
In React, state updates using `setXXX` are asynchronous. This means that even though we expect `setText` to occur first and `storeState` to occur afterward, this order is not guaranteed.
This mismatch in behavior can cause the cursor to jump unexpectedly, since the order of state updates may become inconsistent in certain situations. When this happens, the cursor jumping bug occurs.
---
To fix this bug, I used the `flushSync` API from `react-dom`. This API ensures that state updates using `setXXX` are applied synchronously, so the …

fix: cursor jumps to start of line unexpectedly

---

src/playground/App.js
src/playground/components/Configuration.js

Right now playground crashes because after a change in text or options the `parser` key in URL or LocalStorage sets to `typeScriptESLintParser` meta object rather than "@typescript-eslint/parser" string.
Steps to reproduce.
1 - Open Playground and set the parser to `@typescript-eslint/parser`.
2 - Change something in the text editor, like a space or anything.
3 - Then refresh the page.
https://eslint.org/play/#eyJ0ZXh0IjoiY29uc3QgZm9vID0gMTA7XG5cblxuIiwib3B0aW9ucyI6eyJydWxlcyI6e30sImxhbmd1YWdlT3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6eyJqc3giOnRydWV9LCJzb3VyY2VUeXBlIjoibW9kdWxlIn0sInBhcnNlciI6eyJ2ZXJzaW9uIjoiOC4yOC4wIiwibWV0YSI6eyJuYW1lIjoidHlwZXNjcmlwdC1lc2xpbnQvcGFyc2VyIiwidmVyc2lvbiI6IjguMjguMCJ9fX19fQ==
Added a condition in `storeState` function, if `paser` is …

fix: playground crash due to ts parser
