src/assets/css/styles.css
src/assets/scss/_foundations.scss
src/assets/scss/_prism-syntax-highlighter.scss

- focus outline adjustments
- syntax highlighter colors matching those we have in the new docs

fix: focus outlines

---

src/_includes/partials/analytics.html
src/_includes/partials/footer.html
src/content/pages/index.html
src/content/pages/sponsors.html

Adds Google Analytics and reinstates our tracking of sponsor logo clicks. Also added tracking of donate links.
Fixes #134

chore: Add analytics

---

src/_data/sites/en.yml
src/_includes/partials/footer.html
src/content/pages/index.html
src/content/pages/sponsors.html

chore: Extract homepage text into en.yml

---

src/_includes/partials/faqs.html

fix: fix faq description

---

.github/workflows/data-fetch.yml
tools/commit-data.sh

This workflow will allow us to automatically fetch data for the website each night.
The `DATA_FETCH_TOKEN` secret is tied to the eslintbot user and only has read permission for organization and user data.
Ultimately, this will allow us to remove the Jenkins job that does this for us right now.

chore: Automatically fetch data each night

---

.github/workflows/data-fetch.yml

Forgot to install Node and npm dependencies!

chore: fix data fetch

---

package-lock.json
package.json

Upgrading eleventy-img should fix the issue with the data fetch workflow.

chore: Upgrade dependencies

---

src/_includes/components/navigation.html

Fix [#175](https://github.com/eslint/new.eslint.org/issues/175)

fix: Donate harcoded word

---

tools/fetch-team-data.js

Refers https://github.com/eslint/website/pull/934

fix: check if blog post authors are specified in fetch-team-data script

---

README.md

docs: add link to license in README

---

src/assets/scss/homepage.scss

Fixes 
- https://github.com/eslint/new.eslint.org/issues/190

fix: fix color of selection in copy

---

src/_data/sites/en.yml

docs: fix typo

---

src/_includes/layouts/base.html
src/assets/scss/tokens/typography.scss

This is an addition to https://github.com/eslint/new.eslint.org/pull/213

perf: use system's own flag on non-Windows systems

---

src/_11ty/libs/getCollectionCategories.js
src/assets/scss/blog.scss
src/assets/scss/components/search.scss

fix: correct typos

---

.github/workflows/data-fetch.yml

**Description:**
Updated GitHub actions.

ci: update github actions

---

README.md
package.json

**Description:**
Updated repo URL

chore: update repo url

---

src/_includes/layouts/base.html

Include the full URL as the Open Graph URL.
Fixes #243

fix: Open Graph URL on all pages

---

.eleventy.js
drafts/README.md
src/_11ty/collections/blogposts.js
src/_includes/partials/author_bios/eslintbot.md
src/content/drafts/README.md
src/content/pages/blog.html
src/static/redirects.njk
tools/add-author.js

Adds instructions for how to submit guest posts.
cc @bradzacher @captbaritone

feat: Add instructions for guest posts

---

src/_includes/partials/author_bios/btmills.md

Updated @btmills bio to be in the correct format. Please update as you wish. :)

chore: Update btmills bio

---

src/_includes/layouts/post.html
src/assets/scss/blog.scss

fix: Blog column overflowing

---

.eleventy.js
src/_data/sites/fr.yml
src/_data/sites/pt-br.yml
src/_includes/partials/blog-categories.html
src/content/blog/2015-07-15-eslint-1.0.0-rc-1-released.md
src/content/blog/2018-01-19-eslint-v4.16.0-released.md
src/content/library/card.md
src/content/pages/component-library.html
src/content/pages/sponsors.html

This will throw if we're missing any parameters or accidentally reference substitutions that don't exist. As you'll see in these commits, it catches a number of small accidental omissions.

chore: Enable Nunjucks throwOnUndefined

---

src/static/feed.njk

Resolve https://github.com/eslint/eslint.org/issues/273
- [Old Feed](https://eslint.org/feed.xml)
- [New Feed](https://deploy-preview-274--new-eslint.netlify.app/feed.xml)

fix: correct feed page

---

src/_data/sites/en.yml

Resolve https://github.com/eslint/eslint.org/issues/269

fix: update description of donate page

---

.github/workflows/data-fetch.yml
src/_data/all_authors.json
src/_data/sites/en.yml
src/_data/sites/es.yml
src/_data/sites/fr.yml
src/_data/sites/hi.yml
src/_data/sites/ja.yml
src/_data/sites/pt-br.yml
src/_data/sites/zh-cn.yml
src/_data/team.json
src/content/pages/team.html
tools/fetch-team-data.js

Resolve https://github.com/eslint/eslint.org/issues/283

feat: add website and support team on team page

---

src/playground/App.js
src/playground/utils/debounce.js

- Added `debounce` in code editor with 400ms delay
Resolves #299

fix: missing characters while typing in code editor

---

src/assets/js/search.js

Related pull request on eslint repo https://github.com/eslint/eslint/pull/16187

feat: optimize search result

---

src/_data/sponsors.json
src/content/pages/index.html

Seems like bot added null as URL and the build failed :( 
We might want to update it with a valid URL or go with adding URL only when the URL is available.
I've added valid URL for now from the chrome developer blogs since this made sense to me thoughts?

fix: build failure

---

src/playground/components/Configuration.js

fix: `No options` dropdown background appears white in dark mode 

---

src/playground/scss/editor.scss
src/playground/utils/codemirror-theme.js

| Before | After |
| - | - |
| ![image](https://user-images.githubusercontent.com/45708948/184800350-8d549585-4f50-41fd-8f2c-1c70f4de3a7f.png) | ![image](https://user-images.githubusercontent.com/45708948/184800365-ae3f984d-0f6c-4ae5-b641-a9720bc81f71.png) |

style: auto complete of playground editor

---

src/assets/scss/components/playground-configuration.scss
src/playground/components/Configuration.js
src/playground/components/ShareURL.js

Fixes https://github.com/eslint/eslint.org/issues/310

feat: add collapsibles for right panel contents

---

tools/add-author.js

fixes https://github.com/eslint/eslint.org/issues/331

fix: Update add-author.js to concat empty string instead of null

---

package.json
src/_data/helpers.js
src/content/pages/playground.html

fix: show run install:playground command only for development

---

src/content/blog/2022-10-21-eslint-v8.26.0-released.md

Refs https://github.com/eslint/create-config/issues/41

docs: update `--config` example in v8.26.0 release post

---

src/_includes/components/card.macro.html
src/_includes/components/donation.macro.html
src/_includes/components/profile.macro.html
src/_includes/components/testimonials-slider.html
src/content/pages/404.html
src/content/pages/donate.html

Added `loading="lazy"` for images that miss it

chore: add image lazy loading

---

src/assets/js/search.js

Fixed search bar clear icon flickering and disappearance issue in blog page
Fixes similar to https://github.com/eslint/eslint/issues/16584#issue-1464822578 in blog page

docs: fix searchbar clearbutton

---

.github/ISSUE_TEMPLATE/config.yml

Added issue template configuration file.

chore: add issue template configuration

---

src/assets/js/search.js

debounced the algolia search query to go once instead of every character

perf: debounce search

---

src/_includes/components/language-switcher.html

Improve the experience of language switching
Instead of directing users to homepages in other languages for no reason, they are redirected to corresponding pages in other languages based on the path of the current page

feat: switch language based on current path

---

.github/ISSUE_TEMPLATE/config.yml

Updated name and about. Similar to https://github.com/eslint/eslint/pull/16663

chore: update discord info in issue template

---

src/static/redirects.njk

Added the missing Discord link to the developers channel that is mentioned in the docs.
Closes #384

fix: Add missing /chat/developers link

---

src/content/blog/2022-08-05-new-config-system-part-2.md

Update the example for ESM per https://github.com/eslint/eslintrc/blob/main/README.md#usage

fix: update example code

---

src/content/blog/2022-12-31-eslint-v8.31.0-released.md

Add highlights for the [v8.31.0 release](https://github.com/eslint/eslint/releases/tag/v8.31.0).

docs: Publish v8.31.0 release highlights

---

package.json
src/_data/helpers.js

Fixes https://github.com/eslint/eslint.org/issues/397
https://github.com/eslint/eslint.org/issues/397

fix: local dev broken issue

---

src/content/blog/2023-01-10-eslint-2022-year-review.md

Added a blog post for our 2022 year in review.
n/a
Spelling and grammar :)

feat: blog: 2022 year in review

---

src/content/blog/2023-01-14-eslint-v8.32.0-released.md

Added highlights and published the v8.32.0 release notes.

docs: Publish v8.32.0 release highlights

---

.github/workflows/add-to-triage.yml

Adds triage workflow
Same changes as. https://github.com/eslint/eslint/pull/16740/

chore: adds triage workflow

---

src/static/redirects.njk

Redirect accompanying https://github.com/eslint/eslint/pull/16780
added redirect
https://github.com/eslint/eslint/pull/16780

docs: Redirect 'Get the Source Code' to 'Set up Development Environment'

---

src/content/blog/2023-01-28-eslint-v8.33.0-released.md

Added highlights and published the v8.33.0 release blog post.

docs: Publish v8.33.0 release highlights

---

src/_data/links.json
src/_data/sites/de.yml
src/_data/sites/en.yml
src/_data/sites/es.yml
src/_data/sites/fr.yml
src/_data/sites/hi.yml
src/_data/sites/ja.yml
src/_data/sites/pt-br.yml
src/_data/sites/zh-hans.yml
src/content/blog/2014-06-21-formatter-breaking-change.md
src/content/blog/2018-11-27-jsdoc-end-of-life.md

Removed mention of mailing list
similar to https://github.com/eslint/eslint/pull/16853
N/A

chore: remove mention of mailing list

---

src/content/blog/2023-02-10-eslint-v8.34.0-released.md

Added highlights and published the v8.34.0 release blog post.

docs: Publish v8.34.0 release highlights

---

.github/workflows/ci.yml
.github/workflows/data-fetch.yml

Update CI job.
Use the [Node.js LTS version syntax](https://github.com/actions/setup-node#supported-version-syntax) so we don't have to manually update the node version in the future.
None
No

ci: use LTS node version in workflows

---

src/content/blog/2023-02-26-eslint-v8.35.0-released.md

docs: Publish v8.35.0 release highlights

---

.stylelintrc.js
src/assets/scss/blog.scss
src/assets/scss/components/theme-switcher.scss
src/assets/scss/donations.scss
src/assets/scss/forms.scss
src/assets/scss/foundations.scss
src/assets/scss/playground-layout.scss
src/assets/scss/tokens/typography.scss
src/playground/scss/editor.scss

Replacement of https://github.com/eslint/eslint.org/pull/365
Completely verified the changes locally and checked cascading of rules before and after removing duplicate selectors

chore: remove duplicate scss

---

src/content/blog/2023-03-10-eslint-v8.36.0-released.md

Added highlights and published the v8.36.0 release blog post.

docs: Publish v8.36.0 release highlights

---

src/static/redirects.njk

Added a redirect to the Discord eslint-community channel.

feat: Add eslint-community channel redirect

---

.gitignore
webpack.config.js

fixes https://github.com/eslint/eslint.org/issues/280
Previously build outputs were at `_site` dir where eleventy doesn't detect changes for. We now rather use the actual `asset` folder where the eleventy detects changes and copies files to `_site` folder. Also git ignored the playground and its sourcemap in the asset directory as we dont want that to be commited. 
https://github.com/eslint/eslint.org/issues/280

feat: live reload for playground editor

---

src/content/blog/2023-04-21-eslint-v8.39.0-released.md

Added highlights and published the v8.39.0 release blog post.

docs: Publish v8.39.0 release highlights

---

src/content/blog/2023-05-05-eslint-v8.40.0-released.md

Added highlights and published the v8.40.0 release blog post.

docs: Publish v8.40.0 release highlights

---

src/content/blog/2023-05-19-eslint-v8.41.0-released.md

Added highlights and published the v8.41.0 release blog post.

docs: Publish v8.41.0 release highlights

---

src/content/blog/2023-06-02-eslint-v8.42.0-released.md

Publishes the v8.42.0 release blog post. No highlights this time.

docs: Publish v8.42.0 release

---

src/content/blog/2023-06-30-eslint-v8.44.0-released.md

Added highlights and published the v8.44.0 release blog post.

docs: Publish v8.44.0 release highlights

---

src/content/blog/2023-07-28-eslint-v8.46.0-released.md

Updated the release blog post with highlights.

feat: update v8.46.0 release post

---

tools/fetch-sponsors.js

After talking with Open Collective support, it appears that the GraphQL they gave us for cancelled orders actually doesn't return the correct data. They recommended that we revert these changes to avoid any issues.

chore: Revert OC sponsors fetch changes

---

src/content/blog/2023-08-11-eslint-v8.47.0-released.md

Updating the release blog post.

feat: Release v8.47.0 blog post

---

src/content/blog/2023-08-25-eslint-v8.48.0-released.md

Added highlights and published the v8.48.0 release blog post.

docs: Publish v8.48.0 release highlights

---

src/content/blog/2023-09-08-eslint-v8.49.0-released.md

Added highlights and published the v8.49.0 release blog post.

docs: Publish v8.49.0 release highlights

---

src/content/blog/2023-09-22-eslint-v8.50.0-released.md

Added highlights and published the v8.50.0 release blog post.

docs: Publish v8.50.0 release highlights

---

.gitignore
functions/og.tsx
netlify.toml

Generates an open graph image. Improve the experience of previewing documents in social media.
It consists of six parameters.
https://github.com/eslint/eslint.org/blob/9a7793b41a1ba953b9bba4799853246e29975c14/functions/og.tsx#L30-L36
`/og?title=Core%20Concepts&summary=A%20pluggable%20and%20configurable%20linter%20tool%20for%20identifying%20and%20reporting%20on%20patterns%20in%20JavaScript.%20Maintain%20your%20code%20quality%20with%20ease.%20&is_rule=false&recommended=&fixable=&suggestions=`
`/og?title=no-div-regex&summary=A%20pluggable%20and%20configurable%20linter%20tool%20for%20identifying%20and%20reporting%20on%20patterns%20in%20JavaScript.%20Maintain%20your%20code%20quality%20with%20ease.%20&is_rule=true&recommended=false&fixable=code&suggestions=
`
Close …

feat: generate open graph image in netlify edge function

---

src/content/blog/2023-10-06-eslint-v8.51.0-released.md

Added highlights and published the v8.51.0 release blog post.

docs: Publish v8.51.0 release highlights

---

src/content/blog/2023-10-10-flat-config-rollout-plans.md

Wrote a blog post outlining the rollout plan for flat config.
Please make sure the post is coherent. :)

feat: Announce flat config rollout

---

src/content/blog/2023-10-20-eslint-v8.52.0-released.md

Added highlights and published the v8.52.0 release blog post.

docs: Publish v8.52.0 release highlights

---

src/content/blog/2023-10-10-flat-config-rollout-plans.md

Adds a link to the flat config plugin migration guide in the post about preparing for flat config.

feat: Add plugin migration guide to post

---

src/_includes/partials/author_bios/mdjermanovic.md
src/content/blog/2023-11-03-eslint-v8.53.0-released.md

Added highlights and published the v8.53.0 release blog post.

docs: Publish v8.53.0 release highlights

---

src/content/blog/2023-11-17-eslint-v8.54.0-released.md

Added highlights and published the v8.54.0 release blog post.

docs: Publish v8.54.0 release highlights

---

src/content/blog/2023-12-01-eslint-v8.55.0-released.md

Added highlights and published the v8.55.0 release blog post.

docs: Publish v8.55.0 release highlights

---

src/_data/sites/de.yml
src/_data/sites/en.yml
src/_data/sites/es.yml
src/_data/sites/fr.yml
src/_data/sites/hi.yml
src/_data/sites/ja.yml
src/_data/sites/pt-br.yml
src/_data/sites/zh-hans.yml
src/assets/scss/utilities.scss
src/content/pages/index.html

make latest version on homepage clickable
close https://github.com/eslint/eslint.org/issues/496

chore: make latest version on homepage clickable

---

src/content/blog/2023-12-15-eslint-v8.56.0-released.md

Added highlights and published the v8.56.0 release blog post.

docs: Publish v8.56.0 release highlights

---

src/content/blog/2023-12-29-eslint-v9.0.0-alpha.0-released.md

Added highlights and published the  v9.0.0-alpha.0 release blog post.

docs: Publish v9.0.0-alpha.0 release highlights

---

src/_data/stats.json

I run the `tools/fetch-stats.js` locally to check if it works well now that the current version is a prerelease. If the homepage looks good, I'll merge this.
https://github.com/eslint/eslint.org/pull/502

docs: update stats for v9 prerelease

---

src/content/blog/2024-01-12-eslint-v9.0.0-alpha.1-released.md

Added highlights for the v9.0.0.alpha.1 release

docs: Update v9.0.0-alpha.1 highlights

---

tools/fetch-sponsors.js

The list of one-time contributions on the home page lists ESLint itself.
After investigation, relevant contributions were found https://opencollective.com/typescript-eslint/contributions/719036.
Update GraphQL query statements to [filter contributions of type OUTGOING](https://graphql-docs-v2.opencollective.com/types/AccountOrdersFilter).

fix: treat outgoing donation as  incoming donation

---

src/content/blog/2024-01-26-eslint-v9.0.0-alpha.2-released.md

Added highlights and published the  v9.0.0-alpha.2 release blog post.

docs: Publish v9.0.0-alpha.2 release highlights

---

.gitignore
src/_data/sponsors.json
tools/fetch-sponsors.js

Updated `fetch-sponsors.js`:
- Ensure we check pagination info when fetching sponsors and continue to fetch until we get them all
- Split the requests for sponsors and donors so we only fetch the most recent 100 donors
- Added a `DEBUG` mode that outputs raw responses to disk to aid in debugging future problems
fixes #514

fix: Ensure all sponsorships are pulled from GitHub

---

src/_data/stats.json
tools/release-data.js

Updates "Upcoming Version" on eslint.org to `v9.0.0-beta.0`
Updated `upcomingVersionPrereleaseType` to `beta` and ran the fetch-stats script.
In today's TSC meetings, we decided that we'll start with v9 beta prereleases tomorrow.

docs: switch upcoming version to beta

---

src/content/blog/2024-02-09-eslint-v9.0.0-beta.0-released.md

Added highlights and published the  v9.0.0-beta.0 release blog post.

docs: Publish v9.0.0-beta.0 release highlights

---

src/_includes/layouts/blog.html
src/_includes/layouts/category.html
src/_includes/layouts/components.html
src/_includes/layouts/post.html
src/content/pages/branding.html
src/content/pages/donate.html
src/content/pages/languages.html
src/content/pages/sponsors.html
src/content/pages/team.html

Added `with context` when importing the hero macro. That allows `ad.html` to access global data.
fixes #520

fix: Show ads on all pages

---

src/content/blog/2024-02-21-eslint-2023-year-review.md

Added a blog post reviewing our year and including financials.

feat: 2023 review

---

src/content/blog/2024-02-23-eslint-v8.57.0-released.md

Added highlights and published the v8.57.0 release blog post.

docs: Publish v8.57.0 release highlights

---

src/content/blog/2024-02-23-eslint-v9.0.0-beta.1-released.md

Published the v9.0.0-beta.1 release blog post.

docs: Publish v9.0.0-beta.1 release

---

src/_data/stats.json

Ran `tools/fetch-stats.js` to check if the versions on the homepage will be okay now that we've released v8.57.0 and v9.0.0-beta.1.

docs: update stats

---

src/content/blog/2023-01-10-eslint-2022-year-review.md

Updated the 2022 year in review post.
Updated the financials to match the way we calculated them for 2023 and added the list of top sponsors.

feat: Update 2022 year in review financials

---

.github/workflows/data-fetch.yml

The goal is to refresh version info on the eslint.org homepage right after a new release.
Updated `data-fetch.yml` to also run when a version tag is pushed, which is immediately after each `eslint` release.

chore: update stats after releases

---

src/content/blog/2024-03-08-eslint-v9.0.0-beta.2-released.md

Published the v9.0.0-beta.2 release blog post.

docs: Publish v9.0.0-beta.2 release highlights

---

src/_data/stats.json
tools/release-data.js

Updates "Upcoming Version" on eslint.org to `v9.0.0-rc.0`
Updated `upcomingVersionPrereleaseType` to `rc` and ran the fetch-stats script.
In today's TSC meetings, we decided that we'll start with v9 rc prereleases tomorrow.

docs: switch upcoming version to rc

---

src/_data/all_authors.json
src/content/blog/2024-03-22-eslint-v9.0.0-rc.0-released.md

Published the v9.0.0-rc.0 release blog post.

docs: Publish v9.0.0-rc.0 release highlights

---

src/_data/stats.json
tools/release-data.js

Updates "Upcoming Version" on eslint.org to `v9.0.0`
Updated `upcomingVersionPrereleaseType` to `null` (which means a regular version) and ran the fetch-stats script.
In today's TSC meetings, we decided to release the v9.0.0 final tomorrow.

docs: switch upcoming version to regular

---

src/content/blog/2024-04-05-eslint-config-inspector.md
src/content/blog/2024-04-05-eslint-v9.0.0-released.md

I missed a few features in v9, so I added those into the blog post.

fix: Add missing features to v9 blog post

---

src/content/blog/2024-04-05-eslint-config-inspector.md

Fix small misspelling in blog post.
Edit .md file
n/a
n/a

docs: Fix misspelling in "Config Inspector" blog post

---

src/content/blog/2024-04-19-eslint-v9.1.0-released.md

Published the v9.1.0 release blog post.

docs: Publish v9.1.0 release highlights

---

src/content/blog/2024-04-22-eslint-v9.1.1-released.md

Added highlights to the v9.1.1 release blog post.

docs: Publish v9.1.1 release highlights

---

src/content/blog/2024-04-22-eslint-v9.1.1-released.md

Fixed a typo in the v9.1.1 release highlights
#555

docs: fix typo in v9.1.1 highlights

---

src/content/blog/2024-05-03-eslint-v9.2.0-released.md

Added highlights and published the v9.2.0 release blog post.

docs: Publish v9.2.0 release highlights

---

src/content/pages/index.html

Updated the install command on the homepage to include `@latest`
https://github.com/eslint/eslint/issues/18369

fix: Update setup command on homepage

---

src/_data/sites/es.yml

Update translations.
chore: Update translations. English ---> Spanish
Don't Apply.

chore: Update es.yml

---

src/content/blog/2024-05-09-eslint-compatibility-utilities.md

Added a "shell" label to the first code block to enable proper styling.
fixes #567

fix: Styling of first code block in post

---

src/content/blog/2024-05-17-eslint-v9.3.0-released.md

Added highlights and published the v9.3.0 release blog post.

docs: Publish v9.3.0 release highlights

---

src/content/blog/2024-05-31-eslint-configuration-migrator.md

Added a blog post announcing the config migrator.

feat: Config Migrator Post

---

src/assets/scss/foundations.scss
src/content/pages/index.html

fixes https://github.com/eslint/eslint.org/issues/580
- target only that section
https://github.com/eslint/eslint.org/issues/580

fix: squeezed layout

---

src/content/blog/2024-06-14-eslint-v9.5.0-released.md

Added highlights and published the v9.5.0 release blog post.

docs: Publish v9.5.0 release highlights

---

src/assets/scss/components/alert.scss
src/playground/App.js
src/playground/components/Alert.js
src/playground/components/CodeEditor.js

This PR handles adding functionality to the playground where the user would have the ability to click on a row:col of an alert and would focus and redirection selection/cursor to that position.
Changes to the playground code editor component to inject an extra functionality to scroll to a position.
#587

feat: [playground]Add scrollToPosition functionality to Editor component

---

src/content/blog/2024-07-12-eslint-v9.7.0-released.md

Added highlights and published the v9.7.0 release blog post.

docs: Publish v9.7.0 release highlights

---

src/content/blog/2024-07-05-whats-coming-next-for-eslint.md

Fix the typo in the blog post. Thanks @DamianGlowala

docs: fix typo in blog post

---

src/content/blog/2024-08-09-eslint-v9.9.0-released.md

Added highlights and published the v9.9.0 release blog post.

docs: Publish v9.9.0 release highlights

---

src/_includes/layouts/base.html
src/_includes/layouts/category.html
src/content/pages/generate-categories.njk

Search functionality has been added to all blog categories.
fixes #588

feat: Add search option on all blog categories

---

src/content/blog/2024-08-23-eslint-v9.9.1-released.md

Added highlights and published the v9.9.1 release blog post.

docs: publish v9.9.1 release highlights

---

src/_data/blocked-sponsors.json
src/_data/sponsors.json
tools/fetch-sponsors.js

Added a `blocked-sponsors.json` file to allow us to specify sponsors we don't want to show on the website.

fix: Allow blocking sponsors

---

src/content/blog/2024-09-06-eslint-v9.10.0-released.md

Added highlights and published the v9.10.0 release blog post.

docs: Publish v9.10.0 release highlights

---

src/content/blog/2024-09-16-eslint-v8.57.1-released.md

Added highlights and published the v8.57.1 release blog post.

docs: Publish v8.57.1 release highlights

---

src/content/blog/2024-09-20-eslint-v9.11.0-released.md

Added highlights and published the v9.11.0 release blog post.

docs: Publish v9.11.0 release highlights

---

src/_data/sites/ja.yml

Fixes ja.eslint.org build.
Fixed `ja.yml`.
Failing builds on Netlify.

fix: structure of `ja.yml`

---

src/playground/App.js

Updates the Playground to use the new `eslint/universal` export instead of importing modules directly from `node_modules`.
Updated the Playground to:
1. import `Linter` from `eslint/universal`.
2. Use a simple function that applies a single fix instead of importing `SourceCodeFixer` which is not a public API.
https://github.com/eslint/eslint/issues/18715 and PR https://github.com/eslint/eslint/pull/18883

refactor: use `eslint/universal` export in Playground

---

src/content/blog/2024-09-23-eslint-v9.11.1-released.md

Added highlights and published the v9.11.1 release blog post.

docs: Publish v9.11.1 release highlights

---

src/_data/sponsors.json
tools/fetch-sponsors.js

Updated the `fetch-sponsors.js` script to identify diamond tier sponsors (> =$5,000).
fixes #633

feat: Add diamond tier to fetch-sponsors

---

src/_data/blocked-sponsors.json

At the moment, Open Collective has a bug where it's not showing the "Reject" button in their UI, so we can't reject contributors. This ensures that these contributors do not have their logos displayed until such a time when we can officially reject them (at which point their money will be refunded).

chore: Block inappropriate Open Collective contributors

---

src/content/blog/2024-10-18-eslint-v9.13.0-released.md

Added highlights and published the v9.13.0 release blog post.

docs: Publish v9.13.0 release highlights

---

src/content/blog/2024-11-01-eslint-v9.14.0-released.md

Added highlights and published the v9.14.0 release blog post.

docs: Publish v9.14.0 release highlights

---

src/content/blog/2024-11-01-eslint-v9.14.0-released.md

Added a highlight about the improved performance in v9.14.0.

docs: Mention perf improvement in v9.14 blog

---

src/_includes/components/search.html

- closes https://github.com/eslint/eslint.org/issues/659
- updated url

chore: update url for algolia referrers

---

src/content/blog/2024-11-29-eslint-v9.16.0-released.md

Added highlights and published the v9.16.0 release blog post.

docs: Publish v9.16.0 release highlights

---

src/assets/js/search.js

similar to https://github.com/eslint/eslint/pull/19252
Ensure that the existing functionality remains unaffected

refactor: search result handling with better event listener cleanup

---

src/content/blog/2025-01-24-eslint-v9.19.0-released.md

Added highlights and published the v9.19.0 release blog post.

docs: Publish v9.19.0 release highlights

---

package-lock.json
package.json

The purpose of the pull request is to update the project to Eleventy version 3.
Upgraded to Eleventy v3.
I ran the Upgrade Helper, and everything passed. I also tested the build, and it built without errors. I checked for regressions, but everything seems to work fine.
Fix #644

feat: upgrade to eleventy v3

---

src/content/blog/2025-02-07-eslint-v9.20.0-released.md

Added highlights and published the v9.20.0 release blog post.

docs: Publish v9.20.0 release highlights

---

src/assets/js/search.js

similar to https://github.com/eslint/eslint/pull/19416

fix: keyboard Navigation for Search Results

---

src/content/blog/2025-02-18-eslint-css-support.md

Added a blog post announcing the CSS plugin.

feat: blog: ESLint CSS Support

---

src/content/blog/2025-03-07-flat-config-extends-define-config-global-ignores.md

Added a blog post announcing `defineConfig()` and `globalIgnores()`
Refs https://github.com/eslint/eslint/issues/19116

feat: blog: Evolving flat config with extends

---

src/content/blog/2025-03-07-eslint-v9.22.0-released.md

Added highlights and published the v9.22.0 release blog post.

docs: Publish v9.22.0 release highlights

---

src/content/blog/2025-03-07-eslint-v9.22.0-released.md

Adds more detail to the release notes about `defineConfig()` and `globalIgnores()`

feat: Add more details around defineConfig in release notes

---

src/content/blog/2025-03-07-flat-config-extends-define-config-global-ignores.md

Fixed some typos I found in the new "Evolving flat config with extends" blog.

docs: fix typos in "Evolving flat config with extends" blog

---

src/content/blog/2025-03-21-eslint-v9.23.0-released.md

Added highlights and published the v9.23.0 release blog post.

docs: publish v9.23.0 release highlights

---

src/_data/all_authors.json
src/content/drafts/introducing-bulk-suppressions.md

* https://github.com/eslint/eslint/pull/19159

feat: blog: Introducing bulk suppressions

---

src/content/blog/2025-04-04-eslint-v9.24.0-released.md

Added highlights and published the v9.24.0 release blog post.

docs: Publish v9.24.0 release highlights

---

src/content/blog/2025-04-18-eslint-v9.25.0-released.md

Added highlights and published the v9.25.0 release blog post.

docs: Publish v9.25.0 release highlights

---

src/content/blog/2025-05-02-eslint-v9.26.0-released.md

Added highlights and published the v9.26.0 release blog post.

docs: Publish v9.26.0 release highlights

---

src/content/blog/2025-05-21-eslint-v9.0.0-retrospective.md

Added a blog post describing our learnings from the v9.0.0 release.

feat: v9 retrospective blog post

---

src/_data/blog-dates.json
src/content/blog/2025-06-13-eslint-v9.29.0-released.md

Added highlights and published the v9.29.0 release blog post.

docs: Publish v9.29.0 release highlights

---

src/_data/blog-dates.json
src/content/blog/2025-06-27-eslint-v9.30.0-released.md

Added highlights and published the v9.30.0 release blog post.

docs: publish v9.30.0 release highlights

---

src/_data/blog-dates.json
src/content/blog/2025-07-01-eslint-v9.30.1-released.md

Added highlights and published the v9.30.1 release blog post.

docs: publish v9.30.1 release highlights

---

.gitignore
eslint.config.js

Hello,
In this PR, I've updated ESLint config to use `globalIgnores()` helper function.
I also added `*.code-workspace` and other editor specific configs to the `.gitignore` file.
This is follow-up to https://github.com/eslint/css/pull/145 and https://github.com/eslint/generator-eslint/pull/204.

chore: update `.gitignore` and ESLint config to use `globalIgnores`
